version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: service
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: redis
    restart: always
    ports:
      - "6379:6379"