spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /doc
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: -1

crypto:
  secret: "writelysecret000" # 128 bits
  iv: "writelysecret000" # 128 bits

jwt:
  secret: "writelysecret000writelysecret000" # 256 bits
  access-token-expiration-period: 3600 # 1시간, 60 * 60
  refresh-token-expiration-period: 7776000 # 90일, 90 * 24 * 60 * 60
  join-token-expiration-period: 3600 # 1시간, 60 * 60