spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db-instance-postgres.cv2280c0874d.ap-northeast-2.rds.amazonaws.com:5432/service?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: Writely0101%

server:
  port: 8080

service:
  server:
    url: http://54.180.242.10:8080
  cors:
    origins: http://54.180.242.10:8080, http://localhost:8080, http://localhost:3000