spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/service?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 1234

server:
  port: 8080

service:
  server:
    url: http://localhost:8080
  cors:
    origins: http://localhost:8080, http://localhost:3000