name: Schedule for refresh certification

on:
  schedule:
    - cron: "59 11 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URI }}

      - name: Restart API Server
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --parameters commands='[
              "[ $(docker ps --filter 'publish=8080' -q | wc -l) -gt 0 ] && docker stop $(docker ps --filter 'publish=8080' -q)",
              "docker run --rm -d -p 8080:8080 --name writely-api -v /writely/logs:/writely/logs ${{ secrets.ECR_REGISTRY_URI }}:latest"
            ]' \
            --comment "Restart API Server for apply new certification"